apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-argo-application
  namespace: mongo
spec:
  project: default

  source:
    repoURL: https://github.com/ymjongbin/mongodb-express-k8s.git
    targetRevision: HEAD
    path: k8s
  destination: 
    server: https://kubernetes.default.svc
    namespace: mongo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
